[package]
name = "advent_of_code"
version = "0.2.0"
authors = ["Isaac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.9.0"
rand = "0.8.0"